### ISSUE TITLE
limit log collection by age

### ISSUE THREAD

**Issue by rsvihladremio** [rsvihladremio/dremio-diagnostic-collector#10]
optionally limit log collection by days old 

--only-collect-logs-newer-than 5d
--only-collect-logs-newer-than 2h

This should probably be based on file modified time and has a dependency on #9 being done

**Comment by markcurtis1970** [comment]
perhaps `log-age` or `log-window` ?

**Comment by rsvihladremio** [comment]
`--log-age 5d`
`--log-age 12h`
like that?
