### ISSUE TITLE
make sure 0.3.0 works with awse

### ISSUE THREAD

**Issue by rsvihladremio** [rsvihladremio/dremio-diagnostic-collector#115]
this may imply we have to enable environment detection or a flag to get this to work correctly

**Comment by markcurtis1970** [comment]
Running tool as dremio user fails due to normal coordinator and preview engine being run on same node.

```
$ sudo -u dremio ./ddc local-collect
ERROR: 2023/06/01 13:12:32 local.go:1349: Must set dremio-gclogs-dir manually since we are unable to retrieve gc log location from pid due to error unable to find gc logs due to error 'unable to parse pid from text '3126
16138' due to error strconv.Atoi: parsing "3126\n16138": invalid syntax'
```

**Comment by rsvihladremio** [comment]
so the error there is a nonsense error and unrelated, it should be moved to WARNING as all it affects is the gc log collector
see the text  _Must set dremio-gclogs-dir manually_

what is it that actually fails

**Comment by markcurtis1970** [comment]
Its the fact that on AWSE you get two PIDs

```
$ sudo -u dremio jps | grep DremioDaemon
3126 AwsDremioDaemon
16138 DremioDaemon
```

**Comment by rsvihladremio** [comment]
fixed in https://github.com/rsvihladremio/dremio-diagnostic-collector/pull/121
