### ISSUE TITLE
collect kubernetes configuration when possible

### ISSUE THREAD

**Issue by rsvihladremio** [rsvihladremio/dremio-diagnostic-collector#13]
- collect all describe pod and get pod -o yaml and get pod -o yaml json
- collect controlling statefulset  get pod -o yaml, get pod -o json and describe pod 
- if possible using defaults of helm chart attempt to collect all the known items configured by helm chart

**Comment by markcurtis1970** [comment]
@rsvihladremio - so with this would all the helm items still be kubernetes artefacts? i.e a statefulset is read via `kubectl get statefulset` or are we looking to run some kind of helm commands here?

Some folks may only use the helm charts to generate manifest files and then apply using their own tooling.

**Comment by rsvihladremio** [comment]
I think the raw kubernetes yamls are the principal things we are interested in

**Comment by rsvihladremio** [comment]
we have had some form of this for awhile now
