### ISSUE TITLE
capture jstack

### ISSUE THREAD

**Issue by rsvihladremio** [rsvihladremio/dremio-diagnostic-collector#3]

**Comment by markcurtis1970** [comment]
@rsvihladremio yes I was just looking at this issue and thinking the same, did you want to close this and make it a new issue?

**Comment by rsvihladremio** [comment]
leave this one open still maybe? jfr maybe less present depending on the JVM used but jstack I think is always there

**Comment by markcurtis1970** [comment]
ok roger that

**Comment by rsvihladremio** [comment]
completed in local-collect
