### ISSUE TITLE
Archiving fails silently on unknown suffix

### ISSUE THREAD

**Issue by markcurtis1970** [rsvihladremio/dremio-diagnostic-collector#30]
We silently fail to create the archive if we pass in an unknown extension such as `.tar.gz.  ` or `.blah` the code in `collector.go:archiveDiagDirectory` is not dealing with the unknown extension and silently fails.

We should clean up any suffix spaces and also inform the user if they try to use an unrecognised suffix, perhaps defaulting to `.zip`

**Comment by markcurtis1970** [comment]
This can also cause cleanup of the temp files giving the user the impression that we did not copy any files

**Comment by rsvihladremio** [comment]
we have standardized on using tar.gz for everything, will remove the other options
