### ISSUE TITLE
Windows based collection fails due to kubectl issue

### ISSUE THREAD

**Issue by markcurtis1970** [rsvihladremio/dremio-diagnostic-collector#39]
Need to remove the `C:` part of the path otherwise the colon char is being trated like a namespace / pod according to 

https://github.com/kubernetes/kubernetes/issues/77310

**Comment by nwoodr94** [comment]
I'm still finding this doesn't work with `kubectl cp`

https://github.com/kubernetes/kubernetes/issues/77310#issuecomment-1530142017
