### ISSUE TITLE
cap file sizes over a certain size

### ISSUE THREAD

**Issue by rsvihladremio** [rsvihladremio/dremio-diagnostic-collector#47]
don't collect files over a certain size, set default to 1gb ? 5g?

**Comment by markcurtis1970** [comment]
@rsvihladremio I started to look at this and I had some points:

1. I think you would need to check the size on the remote system _before_ you copy it to the local dir where DDC is running
2. This check can only be done as part of either the file discovery (find command) or alongside it
3. On a large system with many files, how much might this impact performance?
4. I'm working on a fix for #42 currently. This may suffice as a workaround to this until we think of a suitable approach?

Let me know what your thoughts are on the above.

**Comment by rsvihladremio** [comment]
1. agreed
2. yes, one can just run it on each file found
3. well if it can't be integrated with the command it could be substantial..but we could use go routines to make it happen a lot faster
4. agreed

**Comment by rsvihladremio** [comment]
will revisit this later, atm since we went to the explicit log collection this is less important
