### ISSUE TITLE
setup ci to cut a release on tag push

### ISSUE THREAD

**Issue by rsvihladremio** [rsvihladremio/dremio-diagnostic-collector#5]

**Comment by markcurtis1970** [comment]
@rsvihladremio didnt you already fix this in https://github.com/rsvihladremio/dremio-diagnostic-collector/commit/a3566e0f0f8f8aa43cea6464f6e30e5c475eead6

**Comment by rsvihladremio** [comment]
no this is an actual release..so instead of cutting it from our laptops it is pushed out via github runner, I have done this on several repositories prior for example https://github.com/foundev/astra-cli/blob/main/.github/workflows/goreleaser.yml
