### ISSUE TITLE
Support for scale out coordinators in K8s

### ISSUE THREAD

**Issue by markcurtis1970** [rsvihladremio/dremio-diagnostic-collector#66]
Currently we only support the one coordinator. To get logs from a scale out coordinator in K8s we'd need a unique pod label and be able to add it as a argument  under the collection

Ideally we need to just have a list of labels and then collect everything from a list of labels and IPs and delete if the node's role from config or some other means

**Comment by rsvihladremio** [comment]
So looking more closely at this, we currently do actually support this. Unless we can come up with a case where this breaks then I will reopen the issue
